language: java
jdk: openjdk7
deploy:
  provider: heroku
  api_key:
    secure: WX39QvFN0gJ/YISK2lLp5JDtpBBxFDkXQxDBBo8pgt/ZTwbHTguVwlXBoIth1b5k+s2Cjk4uJ0y/UCbgXIfPMn7cHS8DW7ePA7Uk+dN1Sq0sa+GVnziO0osiYlecQtFHKSjltxlt2SUr7VdCmGVlz2FB4gOjPZENbik/Opn9rSY=
  app: helloworld-staging
  on:
    repo: hugpro/helloworld
